#global:
#  scrape_interval: 5s

#scrape_configs:
#  - job_name: 'cadvisor'
#    static_configs:
#      - targets: 
#        - host.docker.internal:8080


global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - cadvisor:8080
        - host.docker.internal:8080
      
